#!/bin/sh -ex

# This picks up NODEPOOL_MIRROR_HOST from the diskimage env-vars and writes
# it here so it is properly picked up by multinode_setup.sh when used as a
# ready-script.

cat <<EOF > /opt/nodepool-scripts/multinode_setup_host.sh
export NODEPOOL_MIRROR_HOST=${NODEPOOL_MIRROR_HOST}
/opt/nodepool-scripts/multinode_setup.sh
EOF
chmod +x /opt/nodepool-scripts/multinode_setup_host.sh
