#!/bin/bash

if [ -z "$DIB_YUM_MINIMAL_BOOTSTRAP_REPOS" ]; then
    exit 0
fi

if [ ! -d $DIB_YUM_MINIMAL_BOOTSTRAP_REPOS ]; then
    mkdir -p $DIB_YUM_MINIMAL_BOOTSTRAP_REPOS
fi

curl https://trunk.rdoproject.org/fedora/delorean-deps.repo -o $DIB_YUM_MINIMAL_BOOTSTRAP_REPOS/dib-mirror-rdo-fedora-stable.repo

